@startuml
abstract class Observable{
- _observers: Observer
+ add(Observer): Observer
+ remove(Observer): None
+ notify():None
}
note bottom:被观察者抽象类
class ObservableImpl{
- data: int
+ change(int):None
}
note bottom:被观察者实现类
abstract class Observer{
+ update(Observable,str):None
}
note bottom:观察者抽象类
class ObserverImpl{
}
note bottom:观察者实现类
ObservableImpl -|> Observable
ObserverImpl -|> Observer
Observer -* Observable
ObserverImpl "订阅"-> ObservableImpl
@enduml